parameters:
  ability_scores:
    costs:
      7: -4
      8: -2
      9: -1
      10: 0
      11: 1
      12: 2
      13: 3
      14: 5
      15: 7
      16: 10
      17: 13
      18: 17
    points:
      low: 10
      standard: 15
      high: 20
      epic: 25
