controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr'
    defaults:
        _locale: 'en'

locale:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: index
        _locale: 'en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
